name: html_main_element
description: Detects the main element of a HTML web page, which represents the core article of that page
version: 1.0.0
homepage: https://github.com/maalexy/html_main_element
author: Alexy Marcell <alexy.marcell@hotmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  html: ^0.13.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
